export const routes = {
  archive: "/archive/:id?",
  audit: "/audit",
  bought: "/bought/:id?",
  calendar: "/calendar/:id?",
  favorites: "/favorites",
  guides: "/guides/:id?",
  hidden: "/hidden",
  history: "/history",
  ic: "/ic",
  images: "/images",
  live: "/live/:id?",
  previous: "/previous/:id?",
  settings: "/settings",
  statistics: "/statistics",
  timeline: "/timeline/:id?",
  updates: "/updates/:id?",
  users: "/users",
};
